Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  KeyPair:
    Description: key pair
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: Instance type
    Type: String
  MyIP:
    Description: local IP allowed to access bastion host
    Type: String

Resources:
  BastionSecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      # SecurityGroups:
      #   - Ref: SecurityGroupsExample
      SecurityGroupIds:
        - Fn::GetAtt: ["BastionSecurityGroups", "GroupId"]
      InstanceType: !Ref InstanceType
      ImageId:
        Fn::ImportValue: !Sub "${EnvironmentName}-AMI"
      KeyName: !Ref KeyPair
      SubnetId:
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: "10"
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-BASTIONINSTANCE
